set(CPACK_PACKAGE_VENDOR "Long Rock Labs")
set(CPACK_PACKAGE_CONTACT "Francesco Ceccon")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Remote miner for the Dark Forest game")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_PACKAGE_DEPENDS "libgmp10, libgmpxx4ldbl, libgomp1, libboost-thread1.71.0, libboost-log1.71.0")

include(CPack)